export {
  login,
  register,
  setAuth,
  authFail,
  clearAuthError,
  clearToken,
  sendEmail,
  clearLoading,
  setNewPassword,
  setResetPasswordSuccess,
  setResetPasswordFail,
  setSendEmailSuccess,
  clearSendEmail,
} from './authenticationSlice';
